services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: adservice
    ports:
      - "5432:5432"